version: '3'
services:
  postgres:
    image: postgres:15.3
    container_name: postgres-local-rti-performance
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rtiperformance